24	dobj_N:su	<sentence id="env_en_make_1">It is unprecedented and in some ways even laughable to imagine that we could actually &lt;span class="target"&gt;make&lt;/span&gt; a conscious choice as a species . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_2">What is at risk of being destroyed is of course not the planet itself but the conditions that have &lt;span class="target"&gt;made&lt;/span&gt; it hospitable for human beings I will not dwell on the science but I want to state a few facts if only to underscore the urgency of our task . </sentence>
76	dobj_N:ncmodprt:su	<sentence id="env_en_make_4">The global recession, we are told, &lt;span class="target"&gt;makes&lt;/span&gt; the task of solving the climate crisis more difficult . </sentence>
24	dobj_N:su	<sentence id="env_en_make_5">But in spite of these fears and doubts, you have continued your work and have continued to &lt;span class="target"&gt;make&lt;/span&gt; steady progress in resolving many issues that once seemed intractable . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_7">Old forests continue to accumulate carbon at a much greater rate than researchers had previously thought, &lt;span class="target"&gt;making&lt;/span&gt; them more important as carbon sinks that must be factored into global climate models, researchers say . </sentence>
49	dobj_N:iobj_PREP:su	<sentence id="env_en_make_11">' '' If they are carbon neutral at 400 years old, how are they going to &lt;span class="target"&gt;make&lt;/span&gt; it to 1, 000 ? </sentence>
24	dobj_N:su	<sentence id="env_en_make_13">This model &lt;span class="target"&gt;makes&lt;/span&gt; a lot of major unfounded assumptions, perhaps the biggest being that humans are incapable of thriving under climate scenarios that differ greatly from the Holocene . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_14">Although there is no doubt that we live in both unusual and challenging times, human induced changes to the Earth system are not happening against a backdrop of 10, 000 years of Holocene climatic stability, and it is precisely our ability to &lt;span class="target"&gt;make&lt;/span&gt; societal changes and adapt to variability that is now required in the face of the dire global anthropogenic changes that Rockström et al . </sentence>
24	dobj_N:su	<sentence id="env_en_make_16">/ ok I exagerated somewhat to &lt;span class="target"&gt;make&lt;/span&gt; a point but that point has also been &lt;span class="target"&gt;made&lt;/span&gt; by the CSIRO . </sentence>
24	dobj_N:su	<sentence id="env_en_make_18">One of the points we &lt;span class="target"&gt;made&lt;/span&gt; was that we really need to sell the case in the US for why cap-and-trade and clean tech are the only way to fly . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_19">It’s possible because we’re not yet &lt;span class="target"&gt;making&lt;/span&gt; the case convincing enough, particularly in the face of dogmatic opposition by some as well as subterfuge from special interests . </sentence>
87	iobj_PREP:su	<sentence id="env_en_make_20">This &lt;span class="target"&gt;makes&lt;/span&gt; for an easy villain in a simple story . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_21">I should have &lt;span class="target"&gt;made&lt;/span&gt; it explicit and I will in the Env-Econ 101 piece but I did n't think that part of the message would be so easily overlooked . </sentence>
24	dobj_N:su	<sentence id="env_en_make_22">( Once they get close to carbonated water as we find in soft drinks, then a few degrees of temperature change could &lt;span class="target"&gt;make&lt;/span&gt; a big difference ! </sentence>
24	dobj_N:su	<sentence id="env_en_make_23">&lt;span class="target"&gt;Making&lt;/span&gt; a gross assumption that the thermometers are homogeneously dispursed around the globe, each thermometer must have encompassed a region from &gt; 20, 000 - 200, 000 mi^2 . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_24">Now there are going to be hurricanes for which another level of intensity will have to be &lt;span class="target"&gt;made&lt;/span&gt; . </sentence>
24	dobj_N:su	<sentence id="env_en_make_26">Surprisingly, perhaps, it is Graham who has been most forceful in &lt;span class="target"&gt;making&lt;/span&gt; the case for effective steps to counter climate change . </sentence>
24	dobj_N:su	<sentence id="env_en_make_27">Graham is a tough partisan, and he was &lt;span class="target"&gt;making&lt;/span&gt; a point about the future of the GOP, which he thinks needs younger people in its ranks . </sentence>
24	dobj_N:su	<sentence id="env_en_make_28">`` Indeed, as the authors observe, it was fashionable in the midst of last February’s snowstorm in Washington for Republicans to &lt;span class="target"&gt;make&lt;/span&gt; jokes about the onset of global warming . </sentence>
24	dobj_N:su	<sentence id="env_en_make_29">“Strobe Talbott and Bill Antholis have &lt;span class="target"&gt;made&lt;/span&gt; an admirable and important effort to move beyond the recent political rancor in Washington . </sentence>
24	dobj_N:su	<sentence id="env_en_make_31">It would not be easy, because richer nations would have to cut their carbon dioxide emissions by mid-century to 80 percent below 2000 levels, and developing nations would have to &lt;span class="target"&gt;make&lt;/span&gt; deep cuts, too . </sentence>
24	dobj_N:su	<sentence id="env_en_make_32">The time has absolutely come to see, discuss, and act upon what we now most certainly know—that visible changes in our environment are transforming the way we must approach the business, personal, and economic decisions we &lt;span class="target"&gt;make&lt;/span&gt; in our lives today . </sentence>
38	dobj_N:obj2_N:su	<sentence id="env_en_make_33">Multiple factors are now in play, &lt;span class="target"&gt;making&lt;/span&gt; this the most exciting time in history to be at the table when the issues of climate change are discussed . </sentence>
24	dobj_N:su	<sentence id="env_en_make_34">The CoolCalifornia Small Business awards program was established to recognize small California businesses ( with less than 100 employees ) and organizations that have demonstrated leadership and &lt;span class="target"&gt;made&lt;/span&gt; notable, voluntary achievements towards reducing their climate impact . </sentence>
24	dobj_N:su	<sentence id="env_en_make_35">The Excellence awards recognize businesses and organizations that have &lt;span class="target"&gt;made&lt;/span&gt; significant efforts to reduce their impact on the climate . </sentence>
24	dobj_N:su	<sentence id="env_en_make_36">Refrigeration company that has &lt;span class="target"&gt;made&lt;/span&gt; great strides to reduce its environmental impact through recycling, re-use and energy efficient cooling technology . </sentence>
38	dobj_N:obj2_N:su	<sentence id="env_en_make_38">The adoption of this rule &lt;span class="target"&gt;makes&lt;/span&gt; California the nation 's only state that has regulated motor vehicles for their contributions to global climate change . </sentence>
32	ccomp__VBARE:su	<sentence id="env_en_make_39">As I’ve noted a number of times, including here most recently, the House has done its job and the President and his team are working very hard to &lt;span class="target"&gt;make&lt;/span&gt; things happen, internationally and domestically . </sentence>
24	dobj_N:su	<sentence id="env_en_make_41">Not surprisingly, when someone as prominent as Stern &lt;span class="target"&gt;makes&lt;/span&gt; a pronouncement as unequivocal - and controversial - as this one, there’s going to be a rapid backlash . </sentence>
24	dobj_N:su	<sentence id="env_en_make_43">The MEF nations’ leaders met in Italy in July and &lt;span class="target"&gt;made&lt;/span&gt; several declarations, among them that “Developing countries among us will promptly undertake actions whose projected effects on emissions represent a meaningful deviation from business as usual in the mid-term …” ( My emphases . </sentence>
38	dobj_N:obj2_N:su	<sentence id="env_en_make_44">Next Tuesday, Prime Minister Reinfeldt and myself are meeting the President of the United States and we will say ‘we are ready to engage, let’s &lt;span class="target"&gt;make&lt;/span&gt; Copenhagen a success.’” John Fredrik Reinfeldt is the Prime Minister of Sweden . </sentence>
24	dobj_N:su	<sentence id="env_en_make_45">He calls on world leaders to follow through on the commitments they’ve been &lt;span class="target"&gt;making&lt;/span&gt; to finalize a strong, smart and thorough agreement in Copenhagen . </sentence>
32	ccomp__VBARE:su	<sentence id="env_en_make_47">The folks at the White House, with President Obama very much driving them, are working assiduously on a number of fronts to &lt;span class="target"&gt;make&lt;/span&gt; this legislation happen . </sentence>
32	ccomp__VBARE:su	<sentence id="env_en_make_50">• Every `` forcing '' produces `` climate feedbacks '' &lt;span class="target"&gt;making&lt;/span&gt; temperature rise faster . </sentence>
32	ccomp__VBARE:su	<sentence id="env_en_make_51">Next, the UN slashed the natural greenhouse effect by 40 per cent from 33C in the climate-physics textbooks to 20C, &lt;span class="target"&gt;making&lt;/span&gt; the man-made additions appear bigger . </sentence>
32	ccomp__VBARE:su	<sentence id="env_en_make_52">Sea level rise is an apt climate change impact to use because the preponderance of projections for how fast it will rise &lt;span class="target"&gt;make&lt;/span&gt; it seem like not much of a threat . </sentence>
24	dobj_N:su	<sentence id="env_en_make_53">By working with large insurance companies, government regulators could encourage rationality when either the private sector or public agencies &lt;span class="target"&gt;make&lt;/span&gt; major investments in coastal urban futures . </sentence>
24	dobj_N:su	<sentence id="env_en_make_54">One link that can be &lt;span class="target"&gt;made&lt;/span&gt;, according to Tom Bonnicksen, a California forest and wildfire expert, is how the fires are contributing to global warming . </sentence>
24	dobj_N:su	<sentence id="env_en_make_56">They might be called upon to &lt;span class="target"&gt;make&lt;/span&gt; even more difficult decisions if the drought continues and a 30 percent or greater sustainable reduction in water use is needed . </sentence>
24	dobj_N:su	<sentence id="env_en_make_57">And no, I did n't &lt;span class="target"&gt;make&lt;/span&gt; connections with people who might fund my work - at least not to my knowledge . </sentence>
24	dobj_N:su	<sentence id="env_en_make_59">Extreme weather, rising seas and skyrocketing oil prices are likely to isolate your city, your town, your community and &lt;span class="target"&gt;make&lt;/span&gt; all of the above abs0lutely necessary . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_62">In times of drought, those who feel the effects of water shortage the most are small water systems and their customers whose reliance on marginal wells, springs, and small creeks &lt;span class="target"&gt;make&lt;/span&gt; them especially sensitive to annual rainfall totals . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_63">A recent law passed by the California Legislature requires all users of publicly-provided water sources have water meters in order that water conservation measures can be &lt;span class="target"&gt;made&lt;/span&gt; more effective . </sentence>
38	dobj_N:obj2_N:su	<sentence id="env_en_make_64">Aiming at people young enough today to be in their prime when today 's efforts to reverse carbon-loading of the atmosphere will &lt;span class="target"&gt;make&lt;/span&gt; a difference in the years that follow, Focus the Nation has an impressive list of advisors, board members, staff and sponsors . </sentence>
24	dobj_N:su	<sentence id="env_en_make_67">No, I do n't expect that I 'll ever actually pronounce it in conversation, but it &lt;span class="target"&gt;makes&lt;/span&gt; my point here, which is that we cant' afford to abandon either of the two approaches to climate change . </sentence>
49	dobj_N:iobj_PREP:su	<sentence id="env_en_make_69">In our own lives, we must &lt;span class="target"&gt;make&lt;/span&gt; the same kinds of changes in our buying and living habits . </sentence>
24	dobj_N:su	<sentence id="env_en_make_70">Adaptations we &lt;span class="target"&gt;make&lt;/span&gt; to climatic change need to be aimed at &lt;span class="target"&gt;making&lt;/span&gt; systems more resilient and healthy now and in the long run . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_71">&lt;span class="target"&gt;Making&lt;/span&gt; a system more resilient could mean reducing pressures that are already stressing the system . </sentence>
24	dobj_N:su	<sentence id="env_en_make_73">`` Five years ago we &lt;span class="target"&gt;made&lt;/span&gt; models predicting how much ice would melt and when, '' said Mr Kallio . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_75">It stresses trees, &lt;span class="target"&gt;making&lt;/span&gt; them vulnerable to bugs and disease . </sentence>
49	dobj_N:iobj_PREP:su	<sentence id="env_en_make_77">I 'm thinking that the best way to penetrate the average U.S. citizen 's crisis fatigue is to &lt;span class="target"&gt;make&lt;/span&gt; the climate change threat a local one - to describe it in terms of what might happen in each person 's back yard . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_78">BROOKLIN, Canada, Jan 2 ( IPS ) - Dan Bloom thinks it 's time to figure out how to build self-sustaining cities in the polar regions because climate change will eventually &lt;span class="target"&gt;make&lt;/span&gt; most of Earth uninhabitable . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_79">Danny Bloom is a U.S. citizen and English teacher living in Taiwan who advocates for building `` self-sustaining cities in the polar regions, '' since `` climate change will eventually &lt;span class="target"&gt;make&lt;/span&gt; most of Earth uninhabitable . </sentence>
32	ccomp__VBARE:su	<sentence id="env_en_make_80">I really don’t care how global warming got started or who’s most at fault, that won’t &lt;span class="target"&gt;make&lt;/span&gt; global warming stop . </sentence>
32	ccomp__VBARE:su	<sentence id="env_en_make_81">Sea level rise is an apt climate change impact to use because the preponderance of projections for how fast it will rise &lt;span class="target"&gt;make&lt;/span&gt; it seem like not much of a threat . </sentence>
24	dobj_N:su	<sentence id="env_en_make_82">By working with large insurance companies, government regulators could encourage rationality when either the private sector or public agencies &lt;span class="target"&gt;make&lt;/span&gt; major investments in coastal urban futures . </sentence>
24	dobj_N:su	<sentence id="env_en_make_83">`` I 'm a guy looking at the reality and wondering when - like the frog - we 're going to cop to what 's going on and start &lt;span class="target"&gt;making&lt;/span&gt; some contingency plans . </sentence>
24	dobj_N:su	<sentence id="env_en_make_84">The plans should have been &lt;span class="target"&gt;made&lt;/span&gt; long ago . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_85">This is being &lt;span class="target"&gt;made&lt;/span&gt; more difficult by zoning restrictions, but some places still seem to be able to force development through, based on local economic benefits . </sentence>
24	dobj_N:su	<sentence id="env_en_make_86">`` We 've &lt;span class="target"&gt;made&lt;/span&gt; so many changes in the natural shape of the land in our watersheds, that property rights get in the way of wise land use . </sentence>
24	dobj_N:su	<sentence id="env_en_make_87">Many political leaders and business managers in cities have enlightened attitudes to the problem of climate change and would like to &lt;span class="target"&gt;make&lt;/span&gt; a contribution to the reduction of greenhouse gas emissions, and so they should . </sentence>
78	iobj_PREP:ncmodprt:su	<sentence id="env_en_make_88">Additionally, state water managers over the summer had to draw down reservoirs to &lt;span class="target"&gt;make&lt;/span&gt; up for the court decision that halted pumping from the delta for several weeks . </sentence>
24	dobj_N:su	<sentence id="env_en_make_89">And while I 'm at it, all those nukes built on th coastlines at sea level to &lt;span class="target"&gt;make&lt;/span&gt; use of the ocean 's voluminous water supply - you 'd better hope the sea does n't rise . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_90">Climate variability will &lt;span class="target"&gt;make&lt;/span&gt; many of our assumptions unstable and our solutions temporary . </sentence>
24	dobj_N:su	<sentence id="env_en_make_92">At the Forum, business and civil society demonstrated support for a Copenhagen deal by showing actions already taken to move to a low-carbon economy and &lt;span class="target"&gt;making&lt;/span&gt; new commitments – individually and in partnership with the UN – to scale up efforts . </sentence>
24	dobj_N:su	<sentence id="env_en_make_93">The EU has already committed to a 20 % reduction in GHG emissions from 1990 levels by 2020 ( along with a 20 % share for renewable energy, and a 20 % boost to energy efficiency ) - and they say they’ll produce a 30 % reduction in GHG if others &lt;span class="target"&gt;make&lt;/span&gt; a similar commitment . </sentence>
24	dobj_N:su	<sentence id="env_en_make_94">Here’s what I think is the heart of the matter : “The most important point to &lt;span class="target"&gt;make&lt;/span&gt; about the leaked correspondence is that it does not undermine the scientific case for cutting emissions of carbon dioxide to fight climate change, which is growing more rather than less compelling . </sentence>
24	dobj_N:su	<sentence id="env_en_make_95">This is a very good thing as it acts as a quality control measure in assuring that future predictions are based on accurate models so that policy wonks can &lt;span class="target"&gt;make&lt;/span&gt; informed decisions . </sentence>
24	dobj_N:su	<sentence id="env_en_make_96">Just 100 days before Hurricane Katrina &lt;span class="target"&gt;made&lt;/span&gt; landfall in Louisiana, he sounded the alarm in the pages of the American Prospect about the Big Easy 's extreme vulnerability to a major storm . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_97">CO2 emissions linked to deforestation in temperate regions : where forests and woodlands are cleared to &lt;span class="target"&gt;make&lt;/span&gt; room for fields and pastures . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_98">Through these efforts, the Climate Institute hopes to &lt;span class="target"&gt;make&lt;/span&gt; individuals at all levels more knowledgeable about the important contribution to global warming due to short-lived gases and aerosols, and about the methods available to reduce emissions of these species in order to reduce the increasing pace of near-term climate change . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_101">A key to &lt;span class="target"&gt;making&lt;/span&gt; C mitigation activities effective and sustainable is to balance it with other ecological and/or environmental, economic, and social goals of land use . </sentence>
24	dobj_N:su	<sentence id="env_en_make_102">Then start &lt;span class="target"&gt;making&lt;/span&gt; some noise of your own . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_103">“The latest results &lt;span class="target"&gt;made&lt;/span&gt; for bleak listening at times, ” she writes . </sentence>
24	dobj_N:su	<sentence id="env_en_make_104">Does nature &lt;span class="target"&gt;make&lt;/span&gt; any spiritual demands on us, or is it purely the supplier in a supply-demand relationship ? ” ( Is nature a mere provider of “ecosystem services ? ” ) For some more on this theme, see Galloping Consumption from the blog about a year back . </sentence>
24	dobj_N:su	<sentence id="env_en_make_105">How do you &lt;span class="target"&gt;make&lt;/span&gt; it ? </sentence>
32	ccomp__VBARE:su	<sentence id="env_en_make_106">Even if levels of CO2 in the atmosphere stayed where they are now, he said, research showed sea levels would rise by between 0.4 and 1.4 metres simply because sea water would continue warming up, which &lt;span class="target"&gt;makes&lt;/span&gt; it expand . </sentence>
24	dobj_N:su	<sentence id="env_en_make_107">ABSTRACT : An attempt is &lt;span class="target"&gt;made&lt;/span&gt; to assess the sensitivity of food production to various aspects of global change and environmental degradation during the next few decades . </sentence>
24	dobj_N:su	<sentence id="env_en_make_108">Bringing into use 10 % of available potential cropland will &lt;span class="target"&gt;make&lt;/span&gt; little difference . </sentence>
24	dobj_N:su	<sentence id="env_en_make_110">ABSTRACT : Estimates of the potential effect of three different climate scenarios for world agriculture are &lt;span class="target"&gt;made&lt;/span&gt; . </sentence>
77	dobj_N:iobj_PREP:ncmodprt:su	<sentence id="env_en_make_111">Scientific studies, typically based on computer models, have for some time examined the effects of postulated climate and atmospheric carbon dioxide changes on specific agroecosystems -- a now common term that defines the interactive unit &lt;span class="target"&gt;made&lt;/span&gt; up of a crop community, such as a field of wheat or corn, and its biophysical environment . </sentence>
24	dobj_N:su	<sentence id="env_en_make_112">In subsequent sections we draw on our own and other modeling studies to show examples of regional and global assessments that have so far been &lt;span class="target"&gt;made&lt;/span&gt;, including discussions of the effects of uncertainty, thresholds, and surprises, and the possible consequences of global warming on agricultural sustainability and food security . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_113">Falling water tables and the resulting increase in the energy needed to pump water will &lt;span class="target"&gt;make&lt;/span&gt; the practice of irrigation more expensive, particularly when with drier conditions more water will be required per acre . </sentence>
24	dobj_N:su	<sentence id="env_en_make_114">For example, were major shifts in crops to be &lt;span class="target"&gt;made&lt;/span&gt;, as from grain to fruit and vegetable production, farmers may find themselves more exposed to marketing problems and credit crises brought on by higher capital and operating costs . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_115">Adaptation can not be taken for granted : improvements in agriculture have always depended upon on the investment that is &lt;span class="target"&gt;made&lt;/span&gt; in agricultural research and infrastructure . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_117">In studying the impacts of climate change, attempts are &lt;span class="target"&gt;made&lt;/span&gt; to link state-of-the-art models developed by researchers in disparate disciplines -- including climatology, agronomy, and economics -- in order to project future food supplies . </sentence>
24	dobj_N:su	<sentence id="env_en_make_119">They will certainly &lt;span class="target"&gt;make&lt;/span&gt; every effort to do so, but the efforts of farmers may well be constrained or even thwarted by factors beyond their control . </sentence>
24	dobj_N:su	<sentence id="env_en_make_120">This coincides with less hurricanes &lt;span class="target"&gt;making&lt;/span&gt; landfall in the United States ( research abstract ) . </sentence>
24	dobj_N:su	<sentence id="env_en_make_121">Kevin Trenberth, climate analysis chief for the National Center for Atmospheric Research in Boulder, Colorado, told the AP that hurricanes hitting land “are not a reliable record” for changes in overall hurricanes, since only a small percentage of storms ever &lt;span class="target"&gt;make&lt;/span&gt; landfall . </sentence>
24	dobj_N:su	<sentence id="env_en_make_122">The storms all &lt;span class="target"&gt;made&lt;/span&gt; landfall around the Gulf of Mexico causing nearly US $ 180bn in damage . </sentence>
49	dobj_N:iobj_PREP:su	<sentence id="env_en_make_123">Food chain contamination through toxic metal absorption from both the environment and from consumption of contaminated food sources could &lt;span class="target"&gt;make&lt;/span&gt; its way to humans, who feed on long-lived land and marine animals such as caribou, seals and whale . </sentence>
24	dobj_N:su	<sentence id="env_en_make_124">This is comprehensive, responsible work and &lt;span class="target"&gt;makes&lt;/span&gt; yet another important argument for getting our collective act together . </sentence>
24	dobj_N:su	<sentence id="env_en_make_125">The senior leadership of the EPA has failed to demonstrate that it has the integrity or independence to &lt;span class="target"&gt;make&lt;/span&gt; decisions based on sound science.” David Doniger, NRDC’s Climate Center Policy Director, said here : “The landmark standards adopted by California and 17 other states will be the single most important step taken so far to curb the heat-trapping pollution that causes global warming . </sentence>
24	dobj_N:su	<sentence id="env_en_make_126">Over the last 10 months, the Administration, under the President’s active leadership, has &lt;span class="target"&gt;made&lt;/span&gt; remarkable progress in addressing climate change and accelerating a clean energy renaissance domestically and abroad ( see a list of accomplishments below ) . </sentence>
24	dobj_N:su	<sentence id="env_en_make_127">Advancing Comprehensive Energy Legislation : Passing comprehensive energy and climate legislation is a top priority for the Administration and significant progress has been &lt;span class="target"&gt;made&lt;/span&gt; . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_128">It has the potential to remove 90 per cent of the CO2 produced by power stations, which would effectively &lt;span class="target"&gt;make&lt;/span&gt; the largest contributor to greenhouse gases carbon-neutral . </sentence>
24	dobj_N:su	<sentence id="env_en_make_129">Congress might be a little preoccupied this week with saving the world from the consequences of the overleveraged, unregulated excesses of the financial industry, nevertheless, they may actually &lt;span class="target"&gt;make&lt;/span&gt; time to find a way to create a package of tax credits that will bolster the renewables industry, keeping its incredible recent momentum going . </sentence>
24	dobj_N:su	<sentence id="env_en_make_130">PM &lt;span class="target"&gt;makes&lt;/span&gt; £1 billion energy pledge is how the 10 Downing Street website describes it . </sentence>
24	dobj_N:su	<sentence id="env_en_make_132">It is very interesting to note, though, that Palin 's entry in the race has generated a huge amount of ink, and climate change is one of the areas on which her views are being &lt;span class="target"&gt;made&lt;/span&gt; known . </sentence>
87	iobj_PREP:su	<sentence id="env_en_make_133">`` Like as the waves &lt;span class="target"&gt;make&lt;/span&gt; towards the pebbled shore ``, One more virtually limitless renewable resource is the ocean . </sentence>
24	dobj_N:su	<sentence id="env_en_make_134">One of the points that de Boer &lt;span class="target"&gt;made&lt;/span&gt; regarding the usefulness of the cap-and-trade system is that it generates interest . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_136">In a word, the US wo n't sign the Copenhagen agreement if China and India, not to mention South Africa and Brazil, among others, are n't required to &lt;span class="target"&gt;make&lt;/span&gt; firm GHG-reduction commitments . </sentence>
24	dobj_N:su	<sentence id="env_en_make_137">`` Vaitheeswaran is quite articulate and had a number of salient points to &lt;span class="target"&gt;make&lt;/span&gt;, among them that there are three pillars of energy instability : poverty, the environment, and geopolitics . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_138">The line about avoiding danger without impeding economic growth basically says we can only do this if we find a way to &lt;span class="target"&gt;make&lt;/span&gt; other energy options as cheap as the world 's mainstays now -- coal and oil . </sentence>
24	dobj_N:su	<sentence id="env_en_make_139">&lt;span class="target"&gt;Making&lt;/span&gt; progress towards the shared vision, and a long-term global goal will require mid-term goals and national plans to achieve them . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_140">But the intertwined constraints of diplomacy and international economic competition seem to &lt;span class="target"&gt;make&lt;/span&gt; firm steps nearly impossible in this arena . </sentence>
24	dobj_N:su	<sentence id="env_en_make_141">The early start of activities under the UNFCCC Adaptation Fund should &lt;span class="target"&gt;make&lt;/span&gt; an important contribution in this respect . </sentence>
24	dobj_N:su	<sentence id="env_en_make_145">“While the statement may appear as a movement forward, we are concerned that it may, in effect, be a regression from what is required to &lt;span class="target"&gt;make&lt;/span&gt; a meaningful contribution to meeting the challenges of climate change, ” van Schalkwyk said in a statement . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_146">While the Statement may appear as a movement forward, we are concerned that it may, in effect, be a regression from what is required to &lt;span class="target"&gt;make&lt;/span&gt; a meaningful contribution to meeting the challenges of climate change . </sentence>
24	dobj_N:su	<sentence id="env_en_make_147">The Clean Technology Fund ( CTF ) and the Strategic Climate Fund ( SCF ) both sound like very good ideas, and the initial funding levels aren’t bad at all – though I believe roughly a factor of 10 higher in some form will be necessary to &lt;span class="target"&gt;make&lt;/span&gt; the significant progress we really need . </sentence>
24	dobj_N:su	<sentence id="env_en_make_148">This administration appears more interested in passing the buck than in passing climate change legislation that would &lt;span class="target"&gt;make&lt;/span&gt; the necessary cuts in global warming emissions . </sentence>
24	dobj_N:su	<sentence id="env_en_make_149">The bottom line is that 50 percent cuts by 2050 is the minimum effort to avert a climate catastrophe, and America must &lt;span class="target"&gt;make&lt;/span&gt; the maximum effort possible as the number one per capita and historical emitter of heat-trapping pollution . </sentence>
24	dobj_N:su	<sentence id="env_en_make_150">I strongly agree with Vice President Gore that we can not drill our way to energy independence, but must fast-track investments in renewable sources of energy like solar power, wind power and advanced biofuels, and those are the investments I will &lt;span class="target"&gt;make&lt;/span&gt; as president.” </sentence>
24	dobj_N:su	<sentence id="env_en_make_151">Higher temperatures lead to drier vegetation that &lt;span class="target"&gt;makes&lt;/span&gt; kindling for mega-fires of the kind that have been raging in Canada, Greece, Russia, China, South America, Australia and Africa . </sentence>
76	dobj_N:ncmodprt:su	<sentence id="env_en_make_153">The leading experts predict that we have less than 10 years to &lt;span class="target"&gt;make&lt;/span&gt; dramatic changes in our global warming pollution lest we lose our ability to ever recover from this environmental crisis . </sentence>
24	dobj_N:su	<sentence id="env_en_make_154">That’s the best investment we can &lt;span class="target"&gt;make&lt;/span&gt; . </sentence>
24	dobj_N:su	<sentence id="env_en_make_156">This is the single most important policy change we can &lt;span class="target"&gt;make&lt;/span&gt; . </sentence>
49	dobj_N:iobj_PREP:su	<sentence id="env_en_make_158">With startling new material on how the last major Ice Epoch could have hastened human evolution, `` Ice Age '' explains why the Earth was once covered in ice - and how that &lt;span class="target"&gt;made&lt;/span&gt; us human . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_159">What &lt;span class="target"&gt;makes&lt;/span&gt; the experiment so interesting was that the GCM contained simulations of the atmosphere, oceans, ice and vegetation, and can therefore be considered to be a much better representation of the climate system than earlier GCMs, containing only the atmospheric component . </sentence>
49	dobj_N:iobj_PREP:su	<sentence id="env_en_make_160">The `` FT Climate Change Challenge `` aims `` to find ideas that are below the radar, being developed by think-tanks, academic institutions or individual entrepreneurs, and identify those that can be taken to scale quickly and &lt;span class="target"&gt;make&lt;/span&gt; a real difference . </sentence>
24	dobj_N:su	<sentence id="env_en_make_162">( I would 've loved to have &lt;span class="target"&gt;made&lt;/span&gt; this conference, but I had other cats to whip, as the French say so disarmingly . </sentence>
24	dobj_N:su	<sentence id="env_en_make_163">I 've also &lt;span class="target"&gt;made&lt;/span&gt; reference to this critical aspect of the fight against global warming a good number of times . </sentence>
24	dobj_N:su	<sentence id="env_en_make_164">Suffice it to say, he is in Speaker Pelosi’s inner circle and would not be &lt;span class="target"&gt;making&lt;/span&gt; this bid without her blessing . </sentence>
24	dobj_N:su	<sentence id="env_en_make_165">“I will &lt;span class="target"&gt;make&lt;/span&gt; a commitment that Al Gore will be at the table and play a central part in us figuring out how we can solve this problem, ” was what he said in April according to this from DeSmogBlog . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_166">Meanwhile, as I noted in my post on the House Energy and Commerce draft climate change bill here : “Another noteworthy point is that the draft &lt;span class="target"&gt;makes&lt;/span&gt; international reforestation and afforestation projects eligible for offsets.” These two key constituencies, the UNFCCC negotiators and John Dingell’s powerful House committee, are going to have an awful lot of influence on the shape of federal and international law in the next couple of years . </sentence>
24	dobj_N:su	<sentence id="env_en_make_167">( See any number of references I’ve &lt;span class="target"&gt;made&lt;/span&gt; to him and his writing at the blog, including talking about the “Step It Up 2007″ campaign . </sentence>
1	su:xcomp__ADJ	<sentence id="env_en_make_168">It’s quite informative, very good at &lt;span class="target"&gt;making&lt;/span&gt; some complex ideas accessible . </sentence>
76	dobj_N:ncmodprt:su	<sentence id="env_en_make_170">If you have n't &lt;span class="target"&gt;made&lt;/span&gt; up your mind and want to see how McCain and Obama are on climate change and the environment, some of this material might help you . </sentence>
76	dobj_N:ncmodprt:su	<sentence id="env_en_make_171">If you have &lt;span class="target"&gt;made&lt;/span&gt; up your mind, this stuff might give you an idea of how President Obama or President McCain might pursue matters of the environment and energy . </sentence>
24	dobj_N:su	<sentence id="env_en_make_173">Having identified possible C conservation measures, the physical, environmental, social, and economic impacts of these measures are examined; and assessment is &lt;span class="target"&gt;made&lt;/span&gt; of how they augment or compete with other services provided by land ( Sections 4.5 - 4.7 ) . </sentence>
24	dobj_N:su	<sentence id="env_en_make_174">The article here reports : “In a recent study, the RAND Corporation estimated that oil from the oil sands generates about 10 to 30 percent more greenhouse gases than conventional crude.” Does this &lt;span class="target"&gt;make&lt;/span&gt; any sense when we’re trying to get to a low-carbon world ? </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_175">The good news is that nearly everybody in leadership positions from the President to his top officials to Senate and House leaders and their committee chairs all seem to be in accord, on the urgency of climate change, the need to transition to a low-carbon world, and to boost the economy by &lt;span class="target"&gt;making&lt;/span&gt; it more energy efficient across the board and by weaning us from the dire environmental problems caused or exacerbated by fossil fuel use . </sentence>
32	ccomp__VBARE:su	<sentence id="env_en_make_176">It’s fair to say that Obama has assembled a team highly capable of getting the job done on climate change and energy - and with the motivation to &lt;span class="target"&gt;make&lt;/span&gt; it happen . </sentence>
32	ccomp__VBARE:su	<sentence id="env_en_make_177">“The $ 646 billion figure, spread over eight years, presumes that a U.S. law to limit carbon emissions will be in place by 2012, and Obama has said he will work with Congress to &lt;span class="target"&gt;make&lt;/span&gt; this happen.” Barbara Boxer has said she wants a bill out this year . </sentence>
24	dobj_N:su	<sentence id="env_en_make_179">Various attempts have been &lt;span class="target"&gt;made&lt;/span&gt; to estimate potential C storage by improved management of agricultural lands . </sentence>
32	ccomp__VBARE:su	<sentence id="env_en_make_180">In Flexibility in Climate Policy : &lt;span class="target"&gt;making&lt;/span&gt; the Kyoto mechanisms work, T. Jackson, K. Begg, S. D. Parkinson, ( eds . </sentence>
1	su:xcomp__ADJ	<sentence id="env_en_make_181">Each year power plants and chemical facilities create many tons of mercury pollution, which &lt;span class="target"&gt;makes&lt;/span&gt; its way into our homes and bodies in fish . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_183">Invasive plants are increasingly expensive to control, and it is widely believed that global warming will &lt;span class="target"&gt;make&lt;/span&gt; the problem worse . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_184">“Not only will I, but I will &lt;span class="target"&gt;make&lt;/span&gt; a commitment that Al Gore will be at the table and play a central part in us figuring out how we can solve this problem . </sentence>
24	dobj_N:su	<sentence id="env_en_make_188">The Vermont Department of Health has raised concerns that the contamination is &lt;span class="target"&gt;making&lt;/span&gt; its way to the nearby Connecticut River . </sentence>
24	dobj_N:su	<sentence id="env_en_make_190">Happily, we are &lt;span class="target"&gt;making&lt;/span&gt; progress, not least through helping to build international agreement as to how countries can work together to meet this shared global challenge . </sentence>
24	dobj_N:su	<sentence id="env_en_make_191">Proposals are beginning to emerge as to how the roughly 25 billion dollars per year needed to &lt;span class="target"&gt;make&lt;/span&gt; a significant impact might be mobilized . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_192">These would be offered to the investment community and could provide companies in, for example, the pensions and insurance sectors, with whom we have been working for the past two years with the Cambridge Programme for Sustainability Leadership, guaranteed returns while, at the same time, &lt;span class="target"&gt;making&lt;/span&gt; available some of the significant resources needed to help slow down deforestation . </sentence>
24	dobj_N:su	<sentence id="env_en_make_193">We are all in this together and perhaps, particularly in the developed world, we need to demonstrate that we understand the current climate change crisis is very much of our own making, all be it unwittingly, and that the credibility of any global solution depends on us being seen to &lt;span class="target"&gt;make&lt;/span&gt; concerted efforts to change our ways . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_194">They’ve stepped up, taken the initiative, and &lt;span class="target"&gt;made&lt;/span&gt; their voices heard, and in doing so, they have helped to effect change—from creating a cosmetics line free of toxic chemicals to trying to conquer global warming to encouraging the use of wind power . </sentence>
24	dobj_N:su	<sentence id="env_en_make_195">Filled with stories from real girls who &lt;span class="target"&gt;made&lt;/span&gt; a difference, plus lots of celebrity green girls who are doing their part to help out, Girls Gone Green gives girls everywhere the inspiration to do something to help their world . </sentence>
24	dobj_N:su	<sentence id="env_en_make_196">It doesn’t matter how small the change is—it only matters that you &lt;span class="target"&gt;make&lt;/span&gt; the effort to bring about that change . </sentence>
24	dobj_N:su	<sentence id="env_en_make_197">Some consideration should be &lt;span class="target"&gt;made&lt;/span&gt; that there is equal evidence that global warming will have no effect on hurricane frequency or intensity and equal evidence that global warming will lower hurricane frequency and intensity . </sentence>
24	dobj_N:su	<sentence id="env_en_make_198">And if I 'm not mistaken, Lindzen ( whom people either love or hate ) argues that just on the surface, it &lt;span class="target"&gt;makes&lt;/span&gt; no sense to say that global warming would lead to more intense storms . </sentence>
1	su:xcomp__ADJ	<sentence id="env_en_make_200">This unique setting &lt;span class="target"&gt;makes&lt;/span&gt; the ice sheet potentially unstable ( IPCC, 2007a ) . </sentence>
24	dobj_N:su	<sentence id="env_en_make_202">A greenhouse gas inventory also provides information on the activities that cause emissions and removals, as well as background on the methods used to &lt;span class="target"&gt;make&lt;/span&gt; the calculations . </sentence>
