24	dobj_N:su	<sentence id="env_en_make_2">Following much political unrest ( conflict with Eritrea, severe famine ), a military rebellion &lt;span class="target"&gt;made&lt;/span&gt; a coup d'état in 1974, and Lieutenant Colonel Mengistu Haile Mariam became the head of state . </sentence>
24	dobj_N:su	<sentence id="env_en_make_3">87 ) . It was partly in response to the observations &lt;span class="target"&gt;made&lt;/span&gt; by the House of People 's Representatives adopted Labour Proclamation No . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_6">Under the previous law, the right to strike was expressly recognized but the pre-strike process was long and &lt;span class="target"&gt;made&lt;/span&gt; legal strike action difficult . </sentence>
24	dobj_N:su	<sentence id="env_en_make_7">For example, pre-strike procedures include : the party initiating the action to give advance notice to the other party – and to the Ministry - with reasons for the strike or lock-out; both parties &lt;span class="target"&gt;making&lt;/span&gt; all efforts to settle through conciliation; cooling-off period of 30 days after the notice; a pro-strike vote by a majority of workers concerned in a meeting in which are present at least two-thirds of the members of the trade union; and maintenance of minimum services for the respect of safety regulations and accident prevention in the undertaking concerned ( Article 158 ) . </sentence>
49	dobj_N:iobj_PREP:su	<sentence id="env_en_make_8">There is a process in the statute where in limited, special circumstances, a request for a work authorization can be &lt;span class="target"&gt;made&lt;/span&gt; to the Commission if the employment of the minor, such as in the case of a child actor, is going to involve odd work hours or other variances from the normal standards set forth in the statute or rules . </sentence>
55	dobj_N:su:xcompto_VBARE	<sentence id="env_en_make_9">Throughout the region efforts are being &lt;span class="target"&gt;made&lt;/span&gt; to attract foreign investors, as are the tourism, energy, telecommunication and small manufacturing sectors in many Caribbean countries . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_10">Strategic alliances and company mergers have &lt;span class="target"&gt;made&lt;/span&gt; job security for workers much more unpredictable . </sentence>
24	dobj_N:su	<sentence id="env_en_make_11">It does n't matter what the issue is, Sunday overtime premium or seniority provisions; if management is to &lt;span class="target"&gt;make&lt;/span&gt; progress, they must remove the roadblock at any cost . </sentence>
56	dobj_N:iobj_PREP:su	<sentence id="env_en_make_13">cash gratuity ( gratification en espèces ) - means a lump sum payment &lt;span class="target"&gt;made&lt;/span&gt; to an employee on termination of employment that recognizes that person 's service to the employer; </sentence>
56	dobj_N:iobj_PREP:su	<sentence id="env_en_make_14">retiring leave ( congé de retraite ) - means a form of termination of employment gratuity &lt;span class="target"&gt;made&lt;/span&gt; to an employee on cessation of employment that recognizes that person 's service to the employer . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_15">`` War &lt;span class="target"&gt;makes&lt;/span&gt; privatization easy : First you destroy the society, and then you let the corporations rebuild it, '' says Hacene Djemam, general secretary of the International Confederation of Arab Trade Unions . </sentence>
56	dobj_N:iobj_PREP:su	<sentence id="env_en_make_16">The International Trade Union Confederation, which is &lt;span class="target"&gt;made&lt;/span&gt; up of 309 labour organisations from more than 156 countries, is holding its inaugural meeting Vienna . </sentence>
24	dobj_N:su	<sentence id="env_en_make_17">Employers should also be required to put any statements regarding job security in such a pre-employment agreement as well so employees are able to more intelligently to &lt;span class="target"&gt;make&lt;/span&gt; decisions whether to accept a job . </sentence>
24	dobj_N:su	<sentence id="env_en_make_18">Interestingly, in the 1940 's an argument was &lt;span class="target"&gt;made&lt;/span&gt; that overtime penalties penalized workers because employers were required to place certain employees on inconvenient `` staggered '' shifts . </sentence>
24	dobj_N:su	<sentence id="env_en_make_21">At non-union worksites management &lt;span class="target"&gt;makes&lt;/span&gt; all the decisions concerning the wages, benefits, and working conditions for professional employees . </sentence>
24	dobj_N:su	<sentence id="env_en_make_24">In a non-union work place, management retains the legal right to &lt;span class="target"&gt;make&lt;/span&gt; all decisions regarding our jobs . </sentence>
24	dobj_N:su	<sentence id="env_en_make_25">Even during difficult times, the employer must justify its actions to the members of the union, who &lt;span class="target"&gt;make&lt;/span&gt; an informed choice . </sentence>
56	dobj_N:iobj_PREP:su	<sentence id="env_en_make_26">The use of temporary contracts has been increasing, &lt;span class="target"&gt;making&lt;/span&gt; workers even more vulnerable to abuse and intimidation . </sentence>
24	dobj_N:su	<sentence id="env_en_make_28">In June 2006, Gold Peak, through its lawyers, wrote to the groups who had signed and supported a postcard campaign, threatening them with legal action unless they &lt;span class="target"&gt;made&lt;/span&gt; an official apology and an immediate payment of HKD 500, 000 damages . </sentence>
24	dobj_N:su	<sentence id="env_en_make_29">The case against the three groups is still active today but Gold Peak has &lt;span class="target"&gt;made&lt;/span&gt; no further arrangement to fix a date for a formal court hearing since September 2007 – the last exchange of legal documents between the two sides . </sentence>
24	dobj_N:su	<sentence id="env_en_make_30">Despite the promises &lt;span class="target"&gt;made&lt;/span&gt; concerning human rights improvements in the run up to the Olympics, workers found themselves detained or arrested, charged and imprisoned for their involvement in collective protest action during the year in the People 's Republic of China . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_33">The enterprise or institution shall strive for a settlement with the reasonable demands &lt;span class="target"&gt;made&lt;/span&gt; by the staff and workers '' . </sentence>
24	dobj_N:su	<sentence id="env_en_make_34">Dispute resolution : In the last decade, the government has &lt;span class="target"&gt;made&lt;/span&gt; considerable efforts to create a dispute resolution system that involves three stages : mediation, arbitration and the courts . </sentence>
56	dobj_N:iobj_PREP:su	<sentence id="env_en_make_37">The fear of detention also &lt;span class="target"&gt;makes&lt;/span&gt; negotiations between workers' representatives and the authorities and employers extremely difficult . </sentence>
24	dobj_N:su	<sentence id="env_en_make_39">Information on Ni Xiafei and Li Keyou has not been &lt;span class="target"&gt;made&lt;/span&gt; public and it is assumed they remain in detention . </sentence>
49	dobj_N:iobj_PREP:su	<sentence id="env_en_make_40">According to new information, several releases of other workers involved in the 1989 protests have been &lt;span class="target"&gt;made&lt;/span&gt; public . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_43">Jordanian labour law was applied in the territories in 1965, and while recent amendments have &lt;span class="target"&gt;made&lt;/span&gt; the legislation more progressive these amendments are not applied to Palestinians . </sentence>
56	dobj_N:iobj_PREP:su	<sentence id="env_en_make_44">The complaints were also &lt;span class="target"&gt;made&lt;/span&gt; to the management, the Ministry of Industry, Trade and Labour in Israel and the Civil Administration . </sentence>
76	dobj_N:ncmodprt:su	<sentence id="env_en_make_45">However, the authorities have not yet visited the factory nor &lt;span class="target"&gt;made&lt;/span&gt; any response . </sentence>
31	dobj_N:iobj_PREP:su	<sentence id="env_en_make_48">In addition, the dramatic rise in violence &lt;span class="target"&gt;makes&lt;/span&gt; it almost impossible to carry out any effective trade union activity . </sentence>
24	dobj_N:su	<sentence id="env_en_make_52">If an employee who is not represented by a trade union elects to keep his or her recall rights or fails to &lt;span class="target"&gt;make&lt;/span&gt; a choice, the employer must send the amount of the termination pay ( and severance pay, if any ) to the Director of Employment Standards, who holds the money in trust . </sentence>
24	dobj_N:su	<sentence id="env_en_make_53">If an employee who is represented by a trade union elects to keep his or her recall rights or fails to &lt;span class="target"&gt;make&lt;/span&gt; a choice, the employer and the trade union must try to come to an arrangement to hold the termination pay ( and severance pay, if any ) in trust for the employee . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_54">By &lt;span class="target"&gt;making&lt;/span&gt; additional financial resources available, parties &lt;span class="target"&gt;make&lt;/span&gt; it possible for postdocs to enhance their employability in the internal and external labour market in a sustainable way and thereby generate an impulse for career formation and personal development . </sentence>
49	dobj_N:iobj_PREP:su	<sentence id="env_en_make_57">In the past, many trade unions have been too anti-European and have failed to organise at European level and thus &lt;span class="target"&gt;make&lt;/span&gt; the ETUC a genuine European trade union . </sentence>
122	dobj_N:iobj_PREP:iobj_PREP:su	<sentence id="env_en_make_58">Union workers in Williamson, N.Y. protest the Dr. Pepper-Snapple company, which demanded a $ 1.50-an-hour pay cut and pension freeze from its Mott 's apple juice employees despite the company &lt;span class="target"&gt;making&lt;/span&gt; record profits of over half a billion a year . </sentence>
54	dobj_N:su:xcompto_VBARE	<sentence id="env_en_make_60">So, it certainly &lt;span class="target"&gt;makes&lt;/span&gt; sense to try and define common principles . </sentence>
49	dobj_N:iobj_PREP:su	<sentence id="env_en_make_61">European social partners could &lt;span class="target"&gt;make&lt;/span&gt; a very positive contribution in the debate if they are able to present a common understanding of the key components of flexicurity . </sentence>
49	dobj_N:iobj_PREP:su	<sentence id="env_en_make_64">The CIO officers advised Mr. Masumuse that they would &lt;span class="target"&gt;make&lt;/span&gt; his life difficult in Rusape unless he relinquished his trade union post . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_66">The Constitution requires union constitutions to &lt;span class="target"&gt;make&lt;/span&gt; their leaders' mandates non-renewable, and foreigners are not allowed to belong to a union 's executive body unless they have lived in the country for 10 years . </sentence>
24	dobj_N:su	<sentence id="env_en_make_67">All competence for &lt;span class="target"&gt;making&lt;/span&gt; employment laws lies with the federal parliament, although enforcement of these laws is primarily through locally-administered labour courts . </sentence>
49	dobj_N:iobj_PREP:su	<sentence id="env_en_make_68">Of seven Octan members to be &lt;span class="target"&gt;made&lt;/span&gt; redundant in October, four resigned from the union and remained employed while two others were dismissed.The union sought help from the police and prosecutor 's offices, but to no avail . </sentence>
77	dobj_N:iobj_PREP:ncmodprt:su	<sentence id="env_en_make_71">Time off from work for class attendance should be &lt;span class="target"&gt;made&lt;/span&gt; up within the same work week ( Monday through Sunday ) by those employees subject to the overtime provisions of the Fair Labor Standards Act, or taken as vacation or unpaid leave . </sentence>
24	dobj_N:su	<sentence id="env_en_make_73">Reka won in the first and second court instances, but his employer &lt;span class="target"&gt;made&lt;/span&gt; a further appeal . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_74">On 26 December, the workers were &lt;span class="target"&gt;made&lt;/span&gt; redundant . </sentence>
77	dobj_N:iobj_PREP:ncmodprt:su	<sentence id="env_en_make_75">Germany is a federal state &lt;span class="target"&gt;made&lt;/span&gt; up of 16 states ( Bundesländer ), to which self government is guaranteed except as otherwise provided by the Basic Law . </sentence>
24	dobj_N:su	<sentence id="env_en_make_77">German labour law &lt;span class="target"&gt;makes&lt;/span&gt; a distinction between ordinary termination ( with notice ), whereby the employment relationship is ended when the period of notice expires ( sec . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_79">The right of participation includes the right to be informed and to &lt;span class="target"&gt;make&lt;/span&gt; recommendations . </sentence>
24	dobj_N:su	<sentence id="env_en_make_80">Spouses, siblings and parents of trade union representatives have been &lt;span class="target"&gt;made&lt;/span&gt; redundant . </sentence>
24	dobj_N:su	<sentence id="env_en_make_85">Strike at Iron Ore plant : refusal to negotiate : In October, workers and members of the trade union at the Gulf Industrial Investment Company 's ( GIIC ) iron ore processing plant voted to go on strike after management allegedly &lt;span class="target"&gt;made&lt;/span&gt; key decisions relating to staff rights and welfare without the union 's consent . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_86">Once an AWA is &lt;span class="target"&gt;made&lt;/span&gt;, awards cease to operate for that employee even after the expiry of the AWA . </sentence>
56	dobj_N:iobj_PREP:su	<sentence id="env_en_make_88">Workers in the private and public sector may join trade unions, including noncitizens, who &lt;span class="target"&gt;make&lt;/span&gt; up the majority of Bahrain 's workforce . </sentence>
24	dobj_N:su	<sentence id="env_en_make_91">Threats to de-register trade unions for &lt;span class="target"&gt;making&lt;/span&gt; international appeals : The JDL filed a case on March 21 with the Labour Court, seeking to de-register the Bangladesh Garments and Industrial Sramik Federation ( BGIWF ), the trade union wing of BCWS . </sentence>
24	dobj_N:su	<sentence id="env_en_make_92">Despite numerous demands &lt;span class="target"&gt;made&lt;/span&gt; by newly established WAs in the final months of the year, there was no report of any collective agreement with a WA . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_93">A common tactic of employers is to dismiss a worker for misconduct, thereby &lt;span class="target"&gt;making&lt;/span&gt; them ineligible to remain a trade union officer . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_95">Arrest and detention of general secretary of Dhaka University Teachers Association ( DUTA ) : Following unrest on the Dhaka University campus which was violently suppressed by police and army personnel, a number of academics &lt;span class="target"&gt;made&lt;/span&gt; public statements decrying the use of violence . </sentence>
24	dobj_N:su	<sentence id="env_en_make_97">Byrne insisted : `` If we want to halve the deficit over four years and protect frontline services, we have to &lt;span class="target"&gt;make&lt;/span&gt; tough but realistic decisions on pay . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_98">A letter from the management confirming the address is usually required, &lt;span class="target"&gt;making&lt;/span&gt; trade unions completely dependent on the good will of the employer . </sentence>
25	dobj_N:su:xcomp__ADJ	<sentence id="env_en_make_99">Compulsory dissolutions : In 2005 a number of amendments to laws and regulations were introduced to &lt;span class="target"&gt;make&lt;/span&gt; trade unions' compulsory dissolution even easier . </sentence>
32	ccomp__VBARE:su	<sentence id="env_en_make_100">SPM believes that the government 's objective is still to obtain the list of trade union members, which could be later used to &lt;span class="target"&gt;make&lt;/span&gt; trade unionists feel vulnerable . </sentence>
24	dobj_N:su	<sentence id="env_en_make_101">The ACFTU and unions in Guangdong Province and Shenzhen called on Huawei to solicit workers' opinions and respect their rights while &lt;span class="target"&gt;making&lt;/span&gt; regulations that will benefit them . </sentence>
24	dobj_N:su	<sentence id="env_en_make_102">According to one observer, since the public debate over the legality of the sackings emerged, authorities issued an order last week to cease all coverage of the Huawei employment issue and to &lt;span class="target"&gt;make&lt;/span&gt; no attempt to question Huawei staff about it . </sentence>
